import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { BellRing } from 'lucide-react'; // For the app logo in the header/footer
import Image from 'next/image';

export default function TermsOfServicePage() {
    const appName = "Remindo";
    const companyName = "PNT Apps"; // Replace with your company name, e.g., "Remindo Inc."
    const contactEmail = "projectninjatech@gmail.com"; // Replace with your contact email
    const effectiveDate = "May 29, 2025"; // Current date

    return (
        <>
            <Head>
                <title>{appName} - Terms of Service</title>
                <meta name="description" content={`Terms of Service for ${appName} - Legal terms governing your use of the app.`} />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="min-h-screen bg-gray-50 text-gray-800 font-sans">
                {/* Header */}
        <header className="bg-white shadow-md py-4">
          <div className="container mx-auto px-4 sm:px-6 flex justify-between items-center">
            <a href="#home" className="flex items-center space-x-2">
              {/* Replaced BellRing with Image component */}
              <Image
                src="/assets/logo.png" // Path to your logo image
                alt={`${appName} Logo`} // Alt text for accessibility
                width={50} // Desired width of the logo
                height={50} // Desired height of the logo (adjust as needed for aspect ratio)
                className="rounded-full" // Add styling like rounded corners if your logo is circular
              />
              {/* <h1 className="text-2xl font-bold text-purple-700">{appName}</h1> */}
            </a>
            <nav>
              <Link href="/" className="text-gray-700 hover:text-purple-600 transition-colors duration-300 font-medium">
                Back to Home
              </Link>
            </nav>
          </div>
        </header>

                {/* Terms of Service Content */}
                <main className="container mx-auto px-4 sm:px-6 py-12 md:py-16 max-w-3xl">
                    <h1 className="text-3xl sm:text-4xl font-extrabold text-purple-700 mb-6 text-center">Terms of Service for {appName}</h1>
                    <p className="text-sm text-gray-500 mb-10 text-center">Last updated: {effectiveDate}</p>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">1. Acceptance of Terms</h2>
                        <p className="text-gray-700 leading-relaxed">
                            Welcome to {appName} (&quot;App&quot;), operated by {companyName} (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;). These Terms of Service (&quot;Terms&quot;) govern your access to and use of the {appName} mobile application.
                        </p>
                        <p className="text-gray-700 leading-relaxed mt-3">
                            By accessing or using the App, you signify that you have read, understood, and agree to be bound by these Terms, as well as our <Link href="/privacy-policy" className="text-purple-600 hover:underline">Privacy Policy</Link>. If you do not agree with these Terms, you must not use the App.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">2. The {appName} Service</h2>
                        <p className="text-gray-700 leading-relaxed">
                            {appName} is a mobile application designed to help you create, manage, and receive reminders and tasks. It provides a simple and intuitive interface to help you stay organized.
                        </p>
                        <p className="text-gray-700 leading-relaxed mt-3">
                            <strong>Key Features and Data Handling:</strong>
                        </p>
                        <ul className="list-disc list-inside ml-4 mt-3 text-gray-700 leading-relaxed">
                            <li className="mb-2">
                                <strong>Local Data Storage:</strong> All your reminder and task data (e.g., reminder content, dates, times) is stored exclusively on your device. We do not collect, store, or have access to your personal reminder data on our servers.
                            </li>
                            <li className="mb-2">
                                <strong>No Account Creation:</strong> {appName} does not require you to create an account or provide any personal information (like your name or email address) to use its core functionalities.
                            </li>
                            <li className="mb-2">
                                <strong>Local Notifications:</strong> All notifications generated by {appName} are local device notifications. We do not control or monitor these notifications from our end.
                            </li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">3. Third-Party Advertising: Google AdMob</h2>
                        <p className="text-gray-700 leading-relaxed">
                            To support the continued development and provide {appName} for free, we integrate Google AdMob for advertising. Please be aware that AdMob may collect certain data to provide personalized and non-personalized ads, such as device information, usage data, and non-precise location information. This data is handled by Google and its advertising partners according to their respective privacy policies.
                        </p>
                        <p className="text-gray-700 leading-relaxed mt-3">
                            For more details on how Google AdMob collects and processes data, please refer to our <Link href="/privacy-policy" className="text-purple-600 hover:underline">Privacy Policy</Link> and Google&apos;s Privacy Policy: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-purple-600 hover:underline">https://policies.google.com/privacy</a>.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">4. User Obligations</h2>
                        <ul className="list-disc list-inside ml-4 mt-3 text-gray-700 leading-relaxed">
                            <li className="mb-2">
                                You must be at least 13 years old to use the App.
                            </li>
                            <li className="mb-2">
                                You agree to use the App only for lawful purposes and in a way that does not infringe the rights of, restrict or inhibit anyone else&apos;s use and enjoyment of the App.
                            </li>
                            <li className="mb-2">
                                You are responsible for maintaining the security of your device and for any data stored locally on it.
                            </li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">5. Intellectual Property</h2>
                        <p className="text-gray-700 leading-relaxed">
                            The App and its original content, features, and functionality are and will remain the exclusive property of <strong>PNT Apps</strong>. The App is protected by copyright laws of India and international copyright laws. You may not use any content from the App without the prior written permission of PNT Apps.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">6. Disclaimer of Warranties</h2>
                        <p className="text-gray-700 leading-relaxed">
                            The App is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. We make no representations or warranties of any kind, express or implied, as to the operation of the App or the information, content, or materials included therein. To the full extent permissible by applicable law, we disclaim all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. We do not warrant that the App will be uninterrupted, error-free, or free of viruses or other harmful components.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">7. Limitation of Liability</h2>
                        <p className="text-gray-700 leading-relaxed">
                            In no event shall {companyName}, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the App; (ii) any conduct or content of any third party on the App; (iii) any content obtained from the App; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">8. Governing Law</h2>
                        <p className="text-gray-700 leading-relaxed">
                            These Terms shall be governed and construed in accordance with the laws of [YOUR_COUNTRY/STATE], without regard to its conflict of law provisions.
                        </p>
                        <p className="text-gray-700 leading-relaxed mt-3">
                            Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">9. Changes to Terms</h2>
                        <p className="text-gray-700 leading-relaxed">
                            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days&apos; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
                        </p>
                        <p className="text-gray-700 leading-relaxed mt-3">
                            By continuing to access or use our App after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the App.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-gray-800 mb-4">10. Contact Us</h2>
                        <p className="text-gray-700 leading-relaxed">
                            If you have any questions about these Terms, please contact us:
                        </p>
                        <p className="text-purple-600 font-semibold mt-3">
                            Email: <a href={`mailto:${contactEmail}`} className="hover:underline">{contactEmail}</a>
                        </p>
                    </section>
                </main>

                {/* Footer (simple version for terms page) */}
                <footer className="bg-gray-900 text-gray-400 py-8 text-center">
                    <div className="container mx-auto px-4 sm:px-6">
                        <Link href="/" className="flex justify-center items-center space-x-2 mb-4">
                            <BellRing className="text-purple-400" size={24} />
                            <p className="text-xl font-bold text-white">{appName}</p>
                        </Link>
                        <p className="text-sm text-gray-500">
                            &copy; {new Date().getFullYear()} {companyName}. All rights reserved.
                        </p>
                    </div>
                </footer>
            </div>
        </>
    );
}